spring:
  application:
    name: auth-backend
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

github:
  base-url: https://github.com
  api-url: https://api.github.com
  client:
    id: Ov23liM793LwGIDgGFhX
    secret: ${GITHUB_CLIENT_SECRET}
  oauth:
    token-uri: /login/oauth/access_token
    user-uri: /user
