openapi: 3.0.3
info:
  title: jdevtree Auth API
  description: Authentication microservice for jdevtree. Supports GitHub OAuth and local JWT auth flows.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /auth/oauth/github:
    post:
      summary: Login with GitHub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'
        '400':
          description: Invalid code or redirect URL

  /auth/token/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Tokens refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseBean'
        '403':
          description: Invalid or reused refresh token

  /auth/logout:
    post:
      summary: Logout and revoke tokens
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: logged_out

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      properties:
        code:
          type: string
        redirectUrl:
          type: string
      required: [code, redirectUrl]

    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required: [refreshToken]

    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required: [refreshToken]

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserView'
        accessToken:
          type: string
        tokenType:
          type: string
        expiresIn:
          type: integer
        refreshToken:
          type: string


    UserView:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        status:
          type: string

    AuthResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/AuthResponse'

    UserResponseBean:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          $ref: '#/components/schemas/UserView'